update README to explain the future of next on netlify
netlify/next-on-netlify pull request #114
Opened 2020-12-13 10:38 UTC by lindsaylevine

2020-12-13 16:28 UTC, sdras requested changes
Looks good! Just a few small changes here.

2020-12-13 16:28 UTC, sdras commented on README.md
>  `next-on-netlify` is a utility for enabling server-side rendering in Next.js on Netlify. It wraps your application in a tiny compatibility layer, so that pages can use Netlify Functions to be server-
This still need to be at the top- people need to know what they're looking at with a sentence or two before anything else. 

We also two links in bullets right after this sentence before moving on:
- build plugin link
- npm package

2020-12-13 16:28 UTC, sdras commented on README.md
> +## The Future of Next.js on Netlify
I'd prefer wording like "Next on Netlify Roadmap" here.

2020-12-13 16:46 UTC, sdras approved these changes
Looks great!

2020-12-13 16:57 UTC, merged

2020-12-15 12:04 UTC, ChrisBAshton commented
Hi 👋 the future looks exciting!

But I think we could do with highlighting that `@netlify/plugin-nextjs` is [not yet ready for use with Netlify CLI](https://github.com/netlify/netlify-plugin-nextjs#cli). I just tried migrating from one to the other before I read the note tucked away in the caveats section! It looks as though `next-on-netlify` is still the recommended approach if you're using the CLI.

2020-12-15 15:01 UTC, lindsaylevine commented
@ChrisBAshton hey chris! thanks so much for calling this out, i agree this was an oversight. my thoughts at the moment:

1. [this](https://github.com/netlify/netlify-plugin-nextjs/issues/58#issuecomment-730439105) is the real issue using the plugin with the CLI, for full transparency. basically, re-runs of `netlify build` or `netlify deploy --build` will fail if you don't get rid of the functions and publish dirs that the plugin generates. reason: we took out the "clean directory" logic for the plugin to support custom functions, but of course, that created the pain points laid out in that issue. all that said, it is _possible_ to use the CLI with the plugin; it just means you have to do the manual clean yourself at the moment. just sayin'

2. that said, since this was a reason for you to _not_ switch, i'm going to prioritize a fix for it. i'll tag you on the issue (and then the PR/release) to keep you updated.

thank you again!!!!!!